### ISSUE TITLE
poeditorPull should skip untranslated strings

### ISSUE THREAD

**Issue by litrik** [lukin0110/poeditor-gradle#6]
When you do a poeditorPull, any untranslated string gets generated as
<string name="some_id"></string>

This means that an empty string will be used in the app instead of the value of the default language. This is probably not what you want.

I suggest to simple skip untranslated strings.

**Comment by lukin0110** [comment]
I have to check this with POEditor if it is possible to skip. The plugin just downloads the files directly from the API.

**Comment by lukin0110** [comment]
In release [0.3.3](https://github.com/lukin0110/poeditor-gradle/releases/tag/0.3.3) it's possible to define filters in your `build.gradle` file.
